### ISSUE TITLE
system error: /usr/lib/libnlopt.so: undefined symbol: nlopt_versionnlopt_

### ISSUE THREAD

**Issue by bluebear94** [jkominek/nlopt#12]
When I try to require the package, I get the following error:

```
> (require nlopt)
; ffi-obj: could not find export from foreign library
;   name: nlopt_versionnlopt_
;   library: libnlopt.so
;   system error: /usr/lib/libnlopt.so: undefined symbol: nlopt_versionnlopt_
; [,bt for context]
```

This seems to be a problem with [`convert-name`](https://github.com/jkominek/nlopt/blob/52946146fe798bb35d1e601500d87e34f4c7365b/nlopt/unsafe.rkt#L98), where replacing `#rx"(.*)$"` with `"nlopt_\\1"` is adding the intended prefix to both ends of the name.

OS: Linux (`uname -a`: `Linux elyundite 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 x86_64 GNU/Linux`)

Racket version: 8.3 (CS)

**Comment by jkominek** [comment]
hmm, yeah looks like the regexp behavior changed in racket between the last time I tried this, and 8.3.

`#rx"(.*)$"` seems to need to be `#rx"^(.*)$"`. and that works fine on the old version of racket i have laying around. if somebody does a real test of that and puts in a PR i'll approve it right away, otherwise i'll test it and get it in myself Real Soon Now.

**Comment by rxg** [comment]
Poked around a bit, and it looks like specifically `regexp-replaces` behaviour changed somewhere between 7.9 and 8.2, though `regexp-replace*` doesn't change (based on 7.9 docs, it looks like `regexp-replaces` should use `regexp-replace*`, so I'm not sure why the present code ever worked).

v7.9:
```
> (regexp-replace* #rx"(.*)$" "world" "hello \\1")
"hello worldhello "
> (regexp-replaces "world" '([#rx"(.*)$" "hello \\1"]))
"hello world"
```

v8.2:
```
> (regexp-replace* #rx"(.*)$" "world" "hello \\1")
"hello worldhello "
> (regexp-replaces "world" '([#rx"(.*)$" "hello \\1"]))
"hello worldhello "
```

Both give the same result for the following:
```
> (regexp-replace* #rx"^(.*)$" "world" "hello \\1")
"hello world"
```

**Comment by rxg** [comment]
PR is here.  I tested it on my system (Mac running Catalina)
#14

**Comment by jkominek** [comment]
Thanks for the assist, @rxg.

Looks like we're all done, @bluebear94. PR is merged. Come on back if you have any other troubles.
